apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceregistry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceregistry
  template:
    metadata:
      labels:
        app: serviceregistry
    spec:
      containers:
        - name: serviceregistry
          image: kbhatt52/serviceregistry:latest
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: serviceregistry
spec:
  selector:
    app: serviceregistry
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
